from connexion import ProblemException


class CustomException(ProblemException):
    pass